# testing for outside docker container
settings:
  loglevel: info
  debug: false

# docker setup needs fixing
docker:
  image:
  image_name:

# setup for discordbot
discordbot:
  charts: false
  # true -> posts charts in all channels or define "charts:false" in the channel where you do not want charts to be posted
  # false -> you can still define "charts:true" per channel
  token: discordbot_token
  channels:
    channel_1:
      id: channel_id
      base_currency: ETH
      quote_currency:
        - USDT
        - BTC
      candle_period: all
      indicator: all
    channel_2:
      id: channel_id
      base_currency: all
      quote_currency: all
      candle_period: all
      indicator:
        - momentum
        - bollinger
        - macd
        - ichimoku
      charts: true
      template: default
    channel_3:
      id: channel_id
      base_currency: all
      quote_currency: all
      candle_period: all
      indicator:
        - momentum
      charts: false
      title_indicator: true
      message: title
  channel_notfound:
    # used when a channel is not found for a token/indicator
    id: channel_id
    base_currency: all
    quote_currency: all
    candle_period: all
    indicator: all

messages:
  default:
    title: "{{base_currency}}, {{quote_currency}}, {{market}}, {{exchange}} {{candle_period}}
            {{ '\n' -}} High: {{price_high}}, Low: {{price_low}}, Close: {{price_close}}
            {{ '\n' -}} {{date}}
            {{ '\n' -}} https://tradingview.com/symbols/{{base_currency}}{{quote_currency}}"
    name: "{{indicator}}"
    value: "value: {{values}}
            {{ '\n' -}} status: {{status}}
            {%- if status == 'hot' %} :rocket: {%- else %} :cry: {%- endif -%}
            {%- if period_count -%} {{ '\n' -}} period: {{period_count}} {%- endif -%}"
  title:
    title: "{{base_currency}}, {{quote_currency}}, {{market}}, {{exchange}} {{candle_period}}
            {{ '\n' -}} High: {{price_high}}, Low: {{price_low}}, Close: {{price_close}}
            {{ '\n' -}} {{date}}
            {{ '\n' -}} https://tradingview.com/symbols/{{base_currency}}{{quote_currency}}
            {{ '\n' -}} value: {{values}}
            {{ '\n' -}} status: {{status}}
            {%- if status == 'hot' %} :rocket: {%- else %} :cry: {%- endif -%}
            {%- if period_count -%} {{ '\n' -}} period: {{period_count}} {%- endif -%}"